project:
  type: website
  output-dir: docs

website:
  title: "Harish B"
  navbar:
    left:
      - href: index.qmd
        text: Posts
      - href: projects.qmd
        text: Projects
    right:
      - href: about.qmd
        text: About
      - icon: github
        href: https://github.com/harishb00
      - icon: linkedin
        href: https://www.linkedin.com/in/harish-b-33b701152/

format:
  html:
    theme: cosmo
    css: styles.css



