project:
  type: website
  output-dir: docs

website:
  title: "Harish B"
  site-url: "https://harishb00.github.io/"
  description: "A simple blog about AI, Machine Learning and Programming."
  navbar:
    left:
      - href: index.qmd
        text: posts
      - href: projects.qmd
        text: pet projects
      - href: favorites.qmd
        text: favorites
    right:
      - icon: github
        href: https://github.com/harishb00
      - icon: linkedin
        href: https://www.linkedin.com/in/harishb00/
      - icon: rss
        href: index.xml

format:
  html:
    theme: default   
    css: styles.css



