project:
  type: website
  output-dir: docs

website:
  title: "Harish B"
  navbar:
    left:
      - href: index.qmd
        text: posts
      - href: projects.qmd
        text: pet projects
    right:
      - href: todo.qmd
        text: todo
      # - href: about.qmd
      #   text: about
      - icon: github
        href: https://github.com/harishb00
      - icon: linkedin
        href: https://www.linkedin.com/in/harishb00/

format:
  html:
    theme: cosmo
    css: styles.css



