---
title: Favorites
page-layout: full
---

## Talks
* [A Little Bit of Slope Makes Up For a Lot of Y-Intercept - John Ousterhout](https://www.youtube.com/watch?v=mE98Is1quwY&list=PLcs1ZorNr2uTGPZPZnBa408qLVHjbMTzT&index=1)
* [The Dangerous Illusion of AI Coding? - Jeremy Howard](https://www.youtube.com/watch?v=dHBEQ-Ryo24)
* [https://www.youtube.com/watch?v=c8_BIamLESg]() (Communication)
* [https://www.youtube.com/watch?v=Unzc731iCUY]() (Communication)

## Posts
* [Teach Yourself Programming in Ten Years - Peter Norvig](https://norvig.com/21-days.html)
* [No Silver Bullet: Essence and Accidents of Software Engineering - Frederick P. Brooks, Jr.](https://www.cs.unc.edu/techreports/86-020.pdf)
* [Impact of AI Productivity - Is it really making us productive?](https://metr.org/blog/2025-07-10-early-2025-ai-experienced-os-dev-study/)
* [The Bitter Lesson - Rich Sutton](http://www.incompleteideas.net/IncIdeas/BitterLesson.html)
* [Advice on Technical Writing - Rich Sutton](https://docs.google.com/document/d/1EKhufclxlvF0RDA3oR0Dp02iTH5biCDguE7Ou7Sprzo/edit?tab=t.0)
* https://github.com/codecrafters-io/build-your-own-x


## Books

### Science & Engineering
* [ ] Six Easy Pieces - Richard Feynman
* [ ] [The Art of Doing Science and Engineering - Richard W. Hamming](https://press.stripe.com/the-art-of-doing-science-and-engineering)
* [ ] [The Elements of Computing Systems: Building a Modern Computer from First Principles](https://www.amazon.in/Elements-Computing-Systems-second-Principles/dp/0262539802)
* [ ] [Crafting Interpreters](https://craftinginterpreters.com/contents.html)
* [ ] [Operating Systems: Three Easy Pieces](https://www.goodreads.com/book/show/17374825-operating-systems)
* [ ] [Designing Data-Intensive Applications, 2nd Edition](https://www.oreilly.com/library/view/designing-data-intensive-applications/9781098119058/)
* [ ] [Database Internals](https://www.oreilly.com/library/view/database-internals/9781492040330/)
* [ ] [The Software Engineer's Guidebook](https://www.engguidebook.com/)
* [ ] [Designing Machine Learning Systems](https://www.oreilly.com/library/view/designing-machine-learning/9781098107956/)
* [ ] [Software Engineering at Google](https://abseil.io/resources/swe-book/html/toc.html)
* [ ] [Hypermedia Systems](https://hypermedia.systems/)
* [ ] A Philosophy of Software Design
* [ ] Tidy First?
* [ ] The Pragmatic Programmer
* [ ] 14 Habits of Highly Productive Developer


### Generic
* [x] The Boy, the Mole, the Fox and the Horse - Charlie Mackesy
* [x] The Artist's Way: A Spiritual Path to Higher Creativity - Julia Cameron
* [ ] The Body Keeps the Score - Bessel Van Der Kolk
* [ ] Drawing on the Right Side of the Brain - Betty Edwards
* [ ] Talent is Overrated: What Really Separates World-class Performers from Everybody Else by Geoffrey Colvin
* [ ] On Writing Well: The Essential Guide to Mastering Nonfiction Writing and Effective Communication
* [ ] The First 90 Days: Proven Strategies for Getting Up to Speed Faster and Smarter, Updated and Expanded
* [ ] Meditations - Marcus Aurelius
* [ ] Katha Upanishad
* [ ] Prashna Upanishad
* [ ] Mundaka Upanishad
* [ ] Thirukural - Thiruvalluvar
* [ ] முதற்கனல் - ஜெயமோகன்
* [ ] Siddhartha - Herman Hesse

