---
title: Quotes
page-layout: full
---

My go-to quotes.

> I know that I know nothing. - *Socrates*

What a line! The more I know about things, the more I come to realize that I don't know.

> I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times. - *Bruce Lee*

I understood this when I deeply read a single research paper for weeks, analyzing between the lines. I learned a lot. Shallow reading gave me the satisfaction of finishing more papers, but deep reading truly made me learn. I can add many such examples. If I deeply understood a topic, I could relate it to many others. That wasn't the case with shallow understanding.

> People are people. - *Jake Morin (My Boss at Nextracker). I'll add to this even I'm part of that.*

Jake told me this during a feedback session: people are people - we shouldn't get angry at them. They might not read our emails or chats and ask the same questions repeatedly. That's just how people are. It's a mantra I repeat when someone bothers me: "People are People." Such a profound thought. Later, I realized I do the same, so I'm part of that too.

> Discipline is a luxury. - *Dr. Renta Chintala Bhargavi (My Professor)*

During my Master's degree, one fine evening she told me this: "Harish, people think that being disciplined is so tough. They don't know that it's a luxury."